# Generated by Django 4.1.5 on 2023-03-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_tag_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
